apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: LoadBalancer
  selector:
    name: rabbitmq
  ports:
  - port: 15672
    name: rabbitmq-management
    targetPort: 15672
    nodePort: 31001
  - port: 5672
    name: amqp
    targetPort: 5672
    nodePort: 31002
